import bcrypt from "bcrypt";

const data = {
  users: [
    {
      name: "Jennie",
      email: "sample@email.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "James",
      email: "user@email.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "this is the first product",
      image: "productImage/plant1.jpg",
      price: 125,
      brand: "Jenny",
      category: "none",
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "name of product1",
      image: "https://www.placehold.it/250x280",
      price: 110,
      brand: "Jenny",
      category: "none",
      countInStock: 0,
      rating: 3,
      numReviews: 12,
      description: "high quality product",
    },
    {
      name: "name of product2",
      image: "https://www.placehold.it/250x280",
      price: 120,
      brand: "Jenny",
      category: "none",
      countInStock: 10,
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "name of product3",
      image: "https://www.placehold.it/250x280",
      price: 120,
      brand: "Jenny",
      category: "none",
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "name of product4",
      image: "https://www.placehold.it/250x280",
      price: 120,
      brand: "Jenny",
      category: "none",
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "name of product5",
      image: "https://www.placehold.it/250x280",
      price: 120,
      brand: "Jenny",
      category: "none",
      countInStock: 10,
      rating: 3.5,
      numReviews: 16,
      description: "high quality product",
    },
    {
      name: "name of product6",
      image: "https://www.placehold.it/250x280",
      price: 120,
      brand: "Jenny",
      category: "none",
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "name of product8",
      image: "https://www.placehold.it/250x280",
      price: 120,
      brand: "Jenny",
      category: "none",
      countInStock: 10,
      rating: 2,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
