const data ={
    products: [
        {
            _id: '1',
            name: 'name of product',
            image: 'https://www.placehold.it/250x280',
            price: 120,
            brand: 'Jenny',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'name of product',
            image: 'https://www.placehold.it/250x280',
            price: 120,
            brand: 'Jenny',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'name of product',
            image: 'https://www.placehold.it/250x280',
            price: 120,
            brand: 'Jenny',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'name of product',
            image: 'https://www.placehold.it/250x280',
            price: 120,
            brand: 'Jenny',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'name of product',
            image: 'https://www.placehold.it/250x280',
            price: 120,
            brand: 'Jenny',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'name of product',
            image: 'https://www.placehold.it/250x280',
            price: 120,
            brand: 'Jenny',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: 'name of product',
            image: 'https://www.placehold.it/250x280',
            price: 120,
            brand: 'Jenny',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'name of product8',
            image: 'https://www.placehold.it/250x280',
            price: 120,
            brand: 'Jenny',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        }
    ]
}

export default data;